### DISCUSSION TITLE
New config for v28.5.0 ?

### DISCUSSION THREAD

**Discussion by bart-newroad** [zkSync-Community-Hub/zksync-developers#1038] [General] [answered]
### ZK chain

Lens

### Environment

Mainnet

### Provide a brief description of the functionality you're trying to implement and the issue you are running into.

Lens uses:

```
      EN_DA_CLIENT: "Avail"
      EN_DA_AVAIL_CLIENT_TYPE: "FullClient"
      EN_DA_BRIDGE_API_URL: "https://bridge-api.avail.so"
      EN_DA_TIMEOUT_MS: "20000"
      EN_DA_API_NODE_URL: "wss://mainnet.avail-rpc.com"
      EN_DA_APP_ID: "26"
```

For v28.2.1 above setting were find but after upgrading to v28.5.0 is gives:

`Error: DA client config is missing`

Tried using this in the docker config like:

      EN_CONSENSUS_CONFIG_PATH: "/configs/mainnet_consensus_config.yaml"
      EN_CONSENSUS_SECRETS_PATH: "/configs/mainnet_consensus_secrets.yaml"

```
da_client:
  avail:
    bridge_api_url: https://bridge-api.avail.so
    timeout_ms: 20000
    full_client:
      api_node_url: wss://mainnet.avail-rpc.com
      app_id: 26    
```  
```
da:
  client: Avail
  seed_phrase: toilet extra
```

What am I missing? I prefer using environment variables like it was running on v28.2.1
