### DISCUSSION TITLE
[ZK Stack] - Contract verifier not accepting requests

### DISCUSSION THREAD

**Discussion by Archethect** [zkSync-Community-Hub/zksync-developers#384] [ZK Stack] [answered]
### Module Affected

- [ ] System contracts (era-system-contracts)
- [ ] Smart contracts (era-contracts)
- [ ] zkEVM (era-zk_evm)
- [ ] Server (zksync-era)
- [ ] Prover (era-boojum)
- [ ] Fee withdrawer (era-fee-withdrawer)
- [ ] Block Explorer (clock-explorer)
- [ ] Portal - Wallet + Bridge (dapp-portal)
- [X] Other (please specify below)

### Rust Version

1.75.0

### Operating System

- [ ] Ubuntu
- [X] MacOS
- [ ] Windows
- [ ] Other (Please specify below)

### Issue Description

Spinning up the docker container for the contract-verifier does not listen to requests on port 3070.

### Expected Behavior

The container binds correctly to port 3070 and the endpoint accepts requests.

### Current Behavior

While trying to spin up the contract-verifier locally, the container spins up and port 3070 is exposed, yet connection requests remain unanswered (for example `http://localhost:3070/contract_verification/zksolc_versions`).

This is the compose file we are using:

```
version: '3.2'
services:
  contract-verifier:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: contract-verifier:latest
    container_name: contract-verifier
    ports:
      - "3070:3070"
    environment:
      - PORT=3070
      - API_WEB3_JSON_RPC_HTTP_PORT=3050
      - CONTRACT_VERIFIER_CONFIG_COMPILATION_TIMEOUT=30
      - CONTRACT_VERIFIER_CONFIG_POLLING_INTERVAL=1000
      - CONTRACT_VERIFIER_COMPILATION_TIMEOUT=30
      - CONTRACT_VERIFIER_POLLING_INTERVAL=1000
      - CONTRACT_VERIFIER_PROMETHEUS_PORT=3314
      - API_WEB3_JSON_RPC_HTTP_URL=http://127.0.0.1:3050
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/zksync_local
    volumes:
      - .:/usr/src/zksync
    env_file:
      - ./etc/env/dev.env
```

logs:

```
2024-02-27 14:19:41 2024-02-27T13:19:41.399104Z  INFO zksync_contract_verifier: No sentry URL was provided

2024-02-27 14:19:43 2024-02-27T13:19:43.589696Z  INFO vise_exporter::exporter: Created metrics exporter with 17 metrics in 6 groups from crates vise_exporter 0.1.0, zksync_consensus_storage 0.1.0, zksync_dal 0.1.0, zksync_queued_job_processor 0.1.0, ...

2024-02-27 14:19:43 2024-02-27T13:19:43.596272Z  INFO vise_exporter::exporter: Starting Prometheus exporter web server on 0.0.0.0:3314
```

### Prior Research

- [X] Yes, I searched for similar issues and did not find any matching ones.
