### DISCUSSION TITLE
[General] <no bin target named `zksync_prover`>

### DISCUSSION THREAD

**Discussion by asdv23** [zkSync-Community-Hub/zksync-developers#476] [General]
### Environment

Testnet

### Provide a brief description of the functionality you're trying to implement.

I wanted to start a complete zksync-era network locally through the [documentation](https://github.com/matter-labs/zksync-era/blob/main/docs/guides/launch.md). Everything went well before, but I encountered an error when starting zk prover, and I didn’t know how to solve it 

### What is the specific issue or error you're encountering?

% zk f cargo +nightly run --release --bin zksync_prover               

error: no bin target named `zksync_prover`

        Did you mean `zksync_server`?

### Can you share the error messages or logs you're receiving, if any?

Sorry, no more logs

### Have you made any recent changes to the contract before encountering this issue?

No, I just used the latest main branch and followed the documentation

### Are there any external libraries or contracts that your contract interacts with?

No

### Can you provide the relevant portions of your contract code where the issue is occurring?

Maybe it has nothing to do with the contract

### Have you tried to isolate the problem, and if so, what were the results?

What does it mean to `isolate the problem`?

### What steps have you already taken to try to resolve the issue?

1. % zk f cargo +nightly run --features gpu --release --bin zksync_prover

error: none of the selected packages contains these features: gpu
2. % zk prover run
error: unknown command 'run'. See 'zk prover --help'.
3. % zk prover
Usage: zk prover [options] [command]

Prover setup related commands

Options:
  -h, --help      display help for command

Commands:
  setup [type]
  help [command]  display help for command

**Comment by bxpana** [comment]
Thanks for reaching out. Did you try again from the beginning to make sure you didn't skip any steps?

**Reply by asdv23** [reply]
Thank you for your attention, I'm sure I haven't missed any errors, if you can please guide me how can I tell which steps I should re-do?

**Reply by bxpana** [reply]
I would start from the beginning of the guide again and see if it works.

**Reply by asdv23** [reply]
Waiting for good news

**Reply by bxpana** [reply]
Going to close this one out in favor of https://github.com/zkSync-Community-Hub/zksync-developers/discussions/481 since it looks like you made some progress

**Reply by asdv23** [reply]
https://github.com/zkSync-Community-Hub/zksync-developers/discussions/481 only solved the problem of zk stack prover-setup execution, but I still can’t get up zk prover?

**Reply by bxpana** [reply]
Apologies, so let's try to get this straight. Are you trying to run a prover and server for ZK Stack?

**Reply by asdv23** [reply]
So the question is, how to start prover through zk stack? I only saw the following commands:
```bash
# zk stack -h
Usage: zk stack [options] [command]

ZK Stack hyperchains management

Options:
  -h, --help              display help for command

Commands:
  init [options]          Wizard for hyperchain creation/configuration
  docker-setup [options]  Generate docker images and compose file for your hyperchain
  prover-setup            Configure the ZK Prover instance for your hyperchain
  demo [options]          Spin up a demo hyperchain with default settings for testing purposes
```

As we can see, zk stack init initializes the environment and starts a zk server by default. prover-setup only downloads some binary files and proof keys. The docker compose file generated by docker-setup is as follows, which is not related to prover, so I How to start the prover driven by zk stack?


hyperchain-zkmantle.yml:
```yaml
version: '3.2'
networks:
  zksync-era_zkstack:
    external: true
volumes:
  artifacts:
services:
  zkstack-core:
    container_name: zkstack-core
    networks:
      - zksync-era_zkstack
    image: zkmantle/server-v2:latest
    command: ["--components", "tree,eth,state_keeper,housekeeper,proof_data_handler"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3071/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    env_file:
      - ./etc/env/zkmantle.env
    environment:
      ZKSYNC_HOME: /
    ports: # assumes default ports in .env
      #- "3312:3312" # prometheus metrics # we need a separate metrics port for each component
      - "3320:3320" # proof_data_handler api
    volumes:
      - artifacts:

  zkstack-apis:
    networks:
      - zksync-era_zkstack
    image: zkmantle/server-v2:latest
    command: ["--components", "http_api,ws_api"]
    env_file:
      - ./etc/env/zkmantle.env
    environment:
      ZKSYNC_HOME: /
      FRI_PROVER_GATEWAY_API_URL: http://zkstack-core:3320
    ports: # assumes default ports in .env
      - "3071:3071" # health
      - "3312:3312" # prometheus metrics # we need a separate metrics port for each component
      - "3050:3050" # http_api
      - "3051:3051" # ws_api
```
