### DISCUSSION TITLE
[General] Run multiple local-nodes in different machines

### DISCUSSION THREAD

**Discussion by aulnes** [zkSync-Community-Hub/zksync-developers#677] [General] [answered]
### Environment

Testnet

### Provide a brief description of the functionality you're trying to implement and the issue you are running into.

I have build a `local-node` image from `zksync-era` main brach, and use the settings from `matter-labs/local-setup` to run the docker compose. I also use the test tools in archived repo `matter-labs/era-tutorial-examples`, and everything went ok.
Although I have had a running local-node(as well as a local chain), I have following questions:

Is it possible to deploy **another local-node** on **another machine** and interact with my local chain?
Just like a zksync-node read the mainnet node and get the chain states.

### Repo Link (Optional)

https://github.com/matter-labs/local-setup

### Additional Details

I use the `zk` tools to build a `local-node` from `zksync-era`, and I add the explorer and other staff(copy from `matter-labs/local-setup/zk-chains-docker-compose.yml`) in the original `docker-compose.yml` file. The local environment running normally, and the contracts can be deployed successfully.
I have not found any docs or specs introducing how to run multiple local-nodes in different machines, are these local-nodes totally independent?

**Comment by alhenaai** [comment]
Running multiple local ZKsync nodes on different machines and having them interact with each other like a network is not directly supported by the standard `matter-labs/local-setup`. Each local node setup typically operates independently, primarily designed for isolated testing and development purposes.

However, if you're looking to simulate a more network-like environment where multiple nodes interact, you might need to customize the networking and synchronization aspects between these nodes manually. This could involve configuring the nodes to communicate over a shared network and ensuring they are synchronized to maintain the same chain state.

For detailed guidance on setting up such an environment, you might need to delve deeper into network configuration and possibly modify the Docker compose files to allow for inter-node communication. Unfortunately, there are no specific documents or specs provided in the current ZKsync documentation that describe running multiple local nodes in different machines in a networked manner.

For further assistance, you might consider reaching out directly to the ZKsync developer community or checking for updates in the [ZKsync GitHub repositories](https://github.com/matter-labs) for any new tools or features that might support this functionality in the future.

Your feedback helps us serve you better. If this fully addresses your question, please give it a thumbs up. If it doesn't, please give it a thumbs down. This will inform the community and team so we can improve our support.

**Reply by aulnes** [reply]
It do resolve some of my doubts, but I still wonder if it possible to use a `external-node` on different machine to catch the local chain?
Just like a `external-node` read the mainnet node.

**Reply by alhenaai** [reply]
Currently, the standard setup provided by ZKsync for local nodes, as described in the documentation and typical use cases, does not explicitly support configuring an external node on a different machine to connect and synchronize with a local chain environment directly. The local setups are generally intended for isolated testing and development, not for creating a network of nodes that mimic the mainnet environment.

If you want an external node to catch or interact with the local chain, you would need to manually configure the network settings to allow external connections and ensure that the external node is set up to recognize and sync with your local chain's state. This might involve:

- Opening the necessary network ports for communication between the nodes.
- Configuring the external node with the correct RPC endpoints of your local node.
- Ensuring both nodes are configured to use compatible network protocols and versions.

This setup goes beyond the typical use case and might require custom development or deeper modifications to the node software and network configurations. It's a more complex scenario that might also involve security considerations, especially if the nodes are exposed over the internet.

For specific guidance on how to achieve this, you might need to consult with network and blockchain development experts or explore more advanced blockchain network setup tutorials that go beyond the basic local node setup.

Your feedback helps us serve you better. If this fully addresses your question, please give it a thumbs up. If it doesn't, please give it a thumbs down. This will inform the community and team so we can improve our support.

**Reply by aulnes** [reply]
May need dev team's help

**Reply by alhenaai** [reply]
For direct assistance from the ZKsync development team, you can engage with them through several channels:

1. **GitHub Discussions**: You can start a discussion or ask questions in the [ZKsync GitHub Discussion forum](https://github.com/zkSync-Community-Hub/zksync-developers/discussions/categories/announcements). This platform is ideal for technical questions and connecting with both the community and the developers.

2. **Discord**: Join the ZKsync [Discord server](https://join.zksync.dev/) where you can chat live with the team and other developers. This is a great place to get real-time help and discuss your setup with peers and ZKsync experts.

3. **Email**: For more formal inquiries or specific assistance, you can reach out via email to [support@zksync.io]. This is suitable for detailed technical support or if you have specific requests or issues that require attention from the support team.

These resources should help you get the specific guidance and support you need from the ZKsync development team.

Your feedback helps us serve you better. If this fully addresses your question, please give it a thumbs up. If it doesn't, please give it a thumbs down. This will inform the community and team so we can improve our support.

**Reply by bxpana** [reply]
I don't see why it wouldn't be possible if you were using 2 different RPC URLs on the same network. What are you trying to do exactly so I can see if what you want is possible right now.

**Reply by aulnes** [reply]
Uploaded my settings.

**Reply by bxpana** [reply]
Appreciate you adding the details. I'll double check and let you know.

**Reply by bxpana** [reply, marked as answer]
Currently we don't have a laid out process for how to do this and it's something that we are working on. For now you can continue to test things out to see if you can get things working and in the future we'll be able to provide clearer details on how to do this.

**Comment by aulnes** [comment]
What I have done:

1. built a `local-node` image from `zksync-era` main branch, using `zk` tools like `zk  docker  build  local-node  --custom-tag "mylocal"` .
2. Running the  `local-node` under the `matter-labs/local-setup/docker-compose.yml` settings, and I added some explorer docker images in the `yml` file to see the block(copy from `matter-labs/local-setup/zk-chains-docker-compose.yml`).
3. Deploy contracts on the local running chain, use `matter-labs/era-tutorial-examples/local-setup-testing`

What I am trying to do:

1. Running another "mylocal2" `local-node`(or `external-node`) on a different machine.
2. Let "mylocal" and "mylocal2" in same network, and they are on the same chain. It is like a `zksync-node` read and recovery the chain history of `main node`. 
3. In short, let "mylocal" and "mylocal2" be decentralized nodes of one chain.


Below is my setting file `docker-compose.yml`:

```
services:
  reth:
    restart: always
    image: "ghcr.io/paradigmxyz/reth:v0.2.0-beta.2"
    volumes:
      - type: bind
        source: ./reth_chaindata
        target: /chaindata

    command: node --dev --datadir /rethdata --http --http.corsdomain "*" --http.addr 0.0.0.0 --http.port 8545  --dev.block-time 300ms --chain /chaindata/reth_config
    environment:
      - RUST_LOG=warn
    ports:
      - 127.0.0.1:15045:8545

  postgres:
    image: "postgres:14"
    # To create necessary databases for block explorer.
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c 'max_connections=200'
    ports:
      - 127.0.0.1:15432:5432
    environment:
      # We bind only to 127.0.0.1, so setting insecure password is acceptable here
      - POSTGRES_PASSWORD=notsecurepassword

  pgadmin4:
    image: dcagatay/pwless-pgadmin4:latest
    ports:
      - 127.0.0.1:15430:80
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: notsecurepassword
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    restart: unless-stopped

  mylocal:
    stdin_open: true
    tty: true
    image: matterlabs/local-node:${INSTANCE_TYPE:-mylocal}
    healthcheck:
      test: curl --fail http://localhost:3071/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 200
      start_period: 30s
    environment:
      - DATABASE_PROVER_URL=postgresql://postgres:notsecurepassword@postgres:5432/prover_local
      - DATABASE_URL=postgresql://postgres:notsecurepassword@postgres:5432/zksync_local
      - ETH_CLIENT_WEB3_URL=http://reth:8545
      - LEGACY_BRIDGE_TESTING=1
    ports:
      - 15100:3050 # JSON RPC HTTP port
      - 15101:3051 # JSON RPC WS port
    depends_on:
      - reth
      - postgres
    volumes:
      - shared_config:/etc/env/target
      - shared_tokens:/etc/tokens
    extra_hosts:
      - host.docker.internal:host-gateway

  # L2 explorer: data-fetcher
  data-fetcher-main:
    platform: linux/amd64
    image: "matterlabs/block-explorer-data-fetcher:latest"
    environment:
      - PORT=3040
      - LOG_LEVEL=verbose
      - BLOCKCHAIN_RPC_URL=http://mylocal:3050
    ports:
      - 127.0.0.1:15104:3040
    restart: unless-stopped

  # L2 explorer: worker
  worker-main:
    platform: linux/amd64
    image: "matterlabs/block-explorer-worker:latest"
    environment:
      - PORT=3001
      - LOG_LEVEL=verbose
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=notsecurepassword
      - DATABASE_NAME=block-explorer
      - BLOCKCHAIN_RPC_URL=http://mylocal:3050
      - DATA_FETCHER_URL=http://data-fetcher-main:3040
      - BATCHES_PROCESSING_POLLING_INTERVAL=1000
    ports:
      - 127.0.0.1:15103:3001
    restart: unless-stopped

  # L2 explorer: API
  api-main:
    platform: linux/amd64
    image: "matterlabs/block-explorer-api:latest"
    environment:
      - PORT=3020
      - METRICS_PORT=3005
      - LOG_LEVEL=verbose
      - DATABASE_URL=postgresql://postgres:notsecurepassword@postgres:5432/block-explorer
    ports:
      - 127.0.0.1:3020:3020 # This is super tricky thing, as the explorer app must depends on api server running on port 3020. Should change the explorer app to have a better solution.
      - 127.0.0.1:15105:3005
    depends_on:
      - worker-main
    restart: unless-stopped

  # L2 explorer: APP
  app:
    platform: linux/amd64
    image: "matterlabs/block-explorer-app:latest"
    environment:
      - NODE_ENV=development
    ports:
      - 15005:3010
    depends_on:
      - api-main
    restart: unless-stopped

  # L1 Blockscout explorer: redis
  redis-db:
    image: 'redis:alpine'
    command: redis-server

  # L1 Blockscout explorer: backend
  backend:
    depends_on:
      - postgres
      - redis-db
    image: blockscout/blockscout:latest
    restart: always
    stop_grace_period: 5m
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      - blockscout/common-blockscout.env
    links:
      - postgres:database
    environment:
      - ETHEREUM_JSONRPC_VARIANT=geth
      - DATABASE_URL=postgresql://postgres:notsecurepassword@postgres:5432/blockscout
      - ETHEREUM_JSONRPC_HTTP_URL=http://reth:8545
      - ETHEREUM_JSONRPC_TRACE_URL=http://reth:8545

  # L1 Blockscout explorer: frontend
  frontend:
    depends_on:
      - backend
    image: ghcr.io/blockscout/frontend:latest
    platform: linux/amd64
    restart: always
    env_file:
      - blockscout/common-frontend.env

  stats:
    depends_on:
      - backend
    image: ghcr.io/blockscout/stats:latest
    platform: linux/amd64
    restart: always
    env_file:
      - blockscout/common-stats.env
    environment:
      - STATS__DB_URL=postgresql://postgres:notsecurepassword@postgres:5432/blockscout_stats
      - STATS__BLOCKSCOUT_DB_URL=postgresql://postgres:notsecurepassword@postgres:5432/blockscout
      - STATS__CREATE_DATABASE=true
      - STATS__RUN_MIGRATIONS=true

  proxy:
    depends_on:
      - backend
      - frontend
      - stats
    image: nginx
    volumes:
      - "./blockscout/proxy:/etc/nginx/templates"
    environment:
      BACK_PROXY_PASS: http://backend:4000
      FRONT_PROXY_PASS: http://frontend:3000
    ports:
      - target: 80
        published: 15001
      - target: 8080
        published: 15002
      - target: 8081
        published: 15003

  sig-provider:
    image: ghcr.io/blockscout/sig-provider:latest
    platform: linux/amd64
    restart: always

  hyperexplorer:
    depends_on:
      mylocal:
        condition: service_healthy
    image: ghcr.io/mm-zk/zksync_tools:latest
    ports:
      - 15000:5000
    volumes:
      - ./hyperexplorer.json:/app/operator/config.json

volumes:
  reth:
  shared_config:
  shared_tokens:
```
