### DISCUSSION TITLE
[ZK Stack] - EigenDA client valid configuration

### DISCUSSION THREAD

**Discussion by kayano** [zkSync-Community-Hub/zksync-developers#962] [ZK Stack] [answered]
### Module Affected

- [ ] System contracts (era-system-contracts)
- [ ] Smart contracts (era-contracts)
- [ ] zkEVM (era-zk_evm)
- [ ] Server (zksync-era)
- [ ] Prover (era-boojum)
- [ ] Fee withdrawer (era-fee-withdrawer)
- [ ] Block Explorer (clock-explorer)
- [ ] Portal - Wallet + Bridge (dapp-portal)
- [X] Other (please specify below)

### Rust Version

1.85.0

### Operating System

- [X] Ubuntu
- [ ] MacOS
- [ ] Windows
- [ ] Other (Please specify below)

### Issue Description

I want to setup https://docs.zksync.io/zk-stack/running/validium to work with EigenDA

### Expected Behavior

Configuring da_client for EigenDA in general.yaml according to docs should not result in zkserver crash.

### Current Behavior

Providing config from docs https://docs.zksync.io/zk-stack/running/validium under FAQ _How to configure EigenDA client?_
```
da_client:
  eigen:
    rpc_node_url: https://disperser-holesky.eigenda.xyz:443
    inclusion_polling_interval_ms: 2000
```
results in zkserver crash during startup with an error https://github.com/matter-labs/zksync-era/blob/3dcc6130cf4e13aa7b557de007b304b49e027806/core/bin/zksync_server/src/node_builder.rs#L131C42-L131C65
```
No config for DA client
```

### Additional Details

After debugging an issue with the config after a lot of trial and error it turns out the config should look like here (at least zkserver is not crashing with the config)
```
da_client:
  eigen:
    disperser_rpc: https://disperser-holesky.eigenda.xyz:443
    settlement_layer_confirmation_depth: 3
    eigenda_eth_rpc: https://ethereum-holesky-rpc.publicnode.com
    eigenda_svc_manager_address: 0xD4A7E1Bd8015057293f0D0A557088c286942e84b
    wait_for_finalization: false
    authenticated: false
    pointsSourceUrl:
      g1_url: https://github.com/Layr-Labs/eigenda-proxy/raw/2fd70b99ef5bf137d7bbca3461cf9e1f2c899451/resources/g1.point
      g2_url: https://github.com/Layr-Labs/eigenda-proxy/raw/2fd70b99ef5bf137d7bbca3461cf9e1f2c899451/resources/g2.point.powerOf2
```
Every single field needs to be provided to the eigen map otherwise the error `No config for DA client`.
Can you confirm this config is correct one for zkserver to work with EigenDA and maybe update your docs to save time others trying to setup EigenDA client?

### Prior Research

- [X] Yes, I searched for similar issues and did not find any matching ones.

**Comment by ly0va** [comment]
Hi @kayano thank you for the feedback! We will update the documentation shortly, meanwhile here is the structure of the config in the code: 
```rust
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub enum PointsSource {
    Path(String),
    /// g1_url, g2_url
    Url((String, String)),
}

/// Configuration for the EigenDA remote disperser client.
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct EigenConfig {
    /// URL of the Disperser RPC server
    pub disperser_rpc: String,
    /// Block height needed to reach in order to consider the blob finalized
    /// a value less or equal to 0 means that the disperser will not wait for finalization
    pub settlement_layer_confirmation_depth: u32,
    /// URL of the Ethereum RPC server
    pub eigenda_eth_rpc: Option<SensitiveUrl>,
    /// Address of the service manager contract
    pub eigenda_svc_manager_address: Address,
    /// Wait for the blob to be finalized before returning the response
    pub wait_for_finalization: bool,
    /// Authenticated dispersal
    pub authenticated: bool,
    /// Points source
    pub points_source: PointsSource,
}

#[derive(Clone, Debug, PartialEq)]
pub struct EigenSecrets {
    pub private_key: PrivateKey,
}
```

Given how flexible deserialization in serde is, your config looks correct, however, here is a more conventional structure:

```yaml
da_client:
  eigen:
    disperser_rpc: https://disperser-holesky.eigenda.xyz:443
    settlement_layer_confirmation_depth: 3
    eigenda_eth_rpc: https://ethereum-holesky-rpc.publicnode.com
    eigenda_svc_manager_address: 0xD4A7E1Bd8015057293f0D0A557088c286942e84b
    wait_for_finalization: false
    authenticated: false
    points_source:
      url:
        - https://github.com/Layr-Labs/eigenda-proxy/raw/2fd70b99ef5bf137d7bbca3461cf9e1f2c899451/resources/g1.point
        - https://github.com/Layr-Labs/eigenda-proxy/raw/2fd70b99ef5bf137d7bbca3461cf9e1f2c899451/resources/g2.point.powerOf2
```

Note that `url: ...` field can alternatively be replaced with `path: /path/to/points`

**Reply by kayano** [reply]
Hi @ly0va, thank for your answer but what you provided as an example config doesn't work for me.
I wrote a simple app which reads `general.yaml` config in similar way zkserver does during startup
```rust
use anyhow::Context as _;
use std::path::PathBuf;
use zksync_core_leftovers::temp_config_store::read_yaml_repr;

fn main() -> anyhow::Result<()> {
    let path = PathBuf::from("general.yaml");
    let configs = read_yaml_repr::<zksync_protobuf_config::proto::general::GeneralConfig>(&path)
        .context("failed decoding general YAML config")?;

    println!("{:?}", configs.da_client_config);
    Ok(())
}
```
having `general.yaml` like
```yaml
da_client:
  eigen:
    disperser_rpc: https://disperser-holesky.eigenda.xyz:443
    settlement_layer_confirmation_depth: 3
    eigenda_eth_rpc: https://ethereum-holesky-rpc.publicnode.com
    eigenda_svc_manager_address: 0xD4A7E1Bd8015057293f0D0A557088c286942e84b
    wait_for_finalization: false
    authenticated: false
    pointsSourceUrl:
      g1_url: https://github.com/Layr-Labs/eigenda-proxy/raw/2fd70b99ef5bf137d7bbca3461cf9e1f2c899451/resources/g1.point
      g2_url: https://github.com/Layr-Labs/eigenda-proxy/raw/2fd70b99ef5bf137d7bbca3461cf9e1f2c899451/resources/g2.point.powerOf2
```
when running `cargo run` it gives
```
Some(Eigen(EigenConfig { disperser_rpc: "https://disperser-holesky.eigenda.xyz:443", settlement_layer_confirmation_depth: 3, eigenda_eth_rpc: Some("https://ethereum-holesky-rpc.publicnode.com/"), eigenda_svc_manager_address: 0xd4a7e1bd8015057293f0d0a557088c286942e84b, wait_for_finalization: false, authenticated: false, points_source: Url(("https://github.com/Layr-Labs/eigenda-proxy/raw/2fd70b99ef5bf137d7bbca3461cf9e1f2c899451/resources/g1.point", "https://github.com/Layr-Labs/eigenda-proxy/raw/2fd70b99ef5bf137d7bbca3461cf9e1f2c899451/resources/g2.point.powerOf2")) }))
```
but with `general.yaml` like from your suggestion
```yaml
da_client:
  eigen:
    disperser_rpc: https://disperser-holesky.eigenda.xyz:443
    settlement_layer_confirmation_depth: 3
    eigenda_eth_rpc: https://ethereum-holesky-rpc.publicnode.com
    eigenda_svc_manager_address: 0xD4A7E1Bd8015057293f0D0A557088c286942e84b
    wait_for_finalization: false
    authenticated: false
    points_source:
      url:
        - https://github.com/Layr-Labs/eigenda-proxy/raw/2fd70b99ef5bf137d7bbca3461cf9e1f2c899451/resources/g1.point
        - https://github.com/Layr-Labs/eigenda-proxy/raw/2fd70b99ef5bf137d7bbca3461cf9e1f2c899451/resources/g2.point.powerOf2
```
`cargo run` gives
```
None
```
I'm using zksync-era repo at versions `core-v26.6.0` 

After changing https://github.com/matter-labs/zksync-era/blob/64d7ede093cd30555d13f6d53875ed071a6c598f/core/lib/zksync_core_leftovers/src/temp_config_store/mod.rs#L33 to `true` and running `cargo run` with your config I'm getting
```
Error: failed decoding general YAML config

Caused by:
    0: failed to read general.yaml
    1: da_client.eigen: unrecognized field name 'points_source' at line 3 column 5
```
What am I missing  here?
